# Generated by Django 5.2.1 on 2025-06-18 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_passwordresetcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetcode',
            name='tentatives',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
