# Generated by Django 5.2.3 on 2025-06-19 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20250619_0651'),
    ]

    operations = [
        # Champs profil conducteur
        migrations.AddField(
            model_name='utilisateur',
            name='depart_habituel',
            field=models.CharField(blank=True, default='Non renseigné', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='horaire_debut',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='horaire_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        # Champs véhicule
        migrations.AddField(
            model_name='utilisateur',
            name='vehicule_marque',
            field=models.CharField(blank=True, default='Marque de voiture', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='vehicule_modele',
            field=models.CharField(blank=True, default='Modèle de voiture', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='vehicule_couleur',
            field=models.CharField(blank=True, default='Couleur du véhicule', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='vehicule_places',
            field=models.PositiveIntegerField(blank=True, default=4, null=True),
        ),
        # Champs préférences passager
        migrations.AddField(
            model_name='utilisateur',
            name='heure_depart_habituel',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
