# Generated by Django 5.2.3 on 2025-06-19 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messagerie', '0002_auto_add_fields'),
    ]

    operations = [
    ]
